[package]
name = "rust_version"
version = "0.1.0"
authors = ["pscott <scottpiriou@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
